---

nginx_user: vagrant

nginx_http_params:
  - index index.php index.html
  - charset utf-8
  - fastcgi_read_timeout 240
  - access_log off
  - open_file_cache max=1000 inactive=20s
  - open_file_cache_valid 30s
  - open_file_cache_min_uses 2
  - open_file_cache_errors on
  - keepalive_requests 1000

nginx_configs:
  upstream_hhvm:
    - upstream hhvm { server unix:/var/run/hhvm/sock; }
  upstream_php:
    - upstream php { server unix:/var/run/php5-fpm.sock; }
  upstream_php5_5_32:
    - upstream php5_5_32 { server unix:/var/run/php-fpm.5.5.32.default.sock; }
  upstream_php5_6_17:
    - upstream php5_6_17 { server unix:/var/run/php-fpm.5.6.17.default.sock; }
  upstream_php7_0_3:
    - upstream php7_0_3 { server unix:/var/run/php-fpm.7.0.3.default.sock; }
  upstream_xhprof:
    - upstream xhprof { server unix:/var/run/php5-fpm.xhprof.sock; }

nginx_fastcgi: |
  client_max_body_size 20M;
  try_files $uri $uri/ /index.php?$args;
  location ~ \.php$ {
    try_files     $uri =404;
    fastcgi_pass  $upstream;
    fastcgi_index index.php;
    include       fastcgi_params;
    fastcgi_param TYPO3_CONTEXT Development;
    fastcgi_param FLOW_CONTEXT Development;
    fastcgi_param FLOW_REWRITEURLS 1;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
  }

nginx_neos_fastcgi: |
  client_max_body_size 20M;
  try_files $uri $uri/ /index.php?$args;
  location ~ \.php$ {
    try_files     $uri =404;
    fastcgi_pass  $upstream;
    fastcgi_index index.php;
    include       fastcgi_params;
    fastcgi_param TYPO3_CONTEXT Development;
    fastcgi_param FLOW_CONTEXT Development;
    fastcgi_param FLOW_REWRITEURLS 1;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param SERVER_NAME "${version}.local.neos.io";
  }

nginx_typo3_fastcgi: |
  client_max_body_size 20M;
  try_files $uri $uri/ /index.php?$args;
  location ~ \.php$ {
    try_files     $uri =404;
    fastcgi_pass  $upstream;
    fastcgi_index index.php;
    include       fastcgi_params;
    fastcgi_param TYPO3_CONTEXT Development;
    fastcgi_param FLOW_CONTEXT Development;
    fastcgi_param FLOW_REWRITEURLS 1;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param SERVER_NAME "${version}.local.typo3.org";
  }

nginx_typo3_404_redirect: |
  location @404 {
    rewrite ^ $scheme://local.typo3.org;
  }

nginx_neos_404_redirect: |
  location @404 {
    rewrite ^ $scheme://local.neos.io;
  }

nginx_typo3_neos_resources: |
  location ~ "^/_Resources/Persistent/" {
    if ($version ~ (1.0|1.1|1.2)) {
      expires max;
      rewrite "(.{40})/.+\.(.+)" /_Resources/Persistent/$1.$2 break;
      rewrite "([a-z0-9]+/(.+/)?[a-f0-9]{40})/.+\.(.+)" /_Resources/Persistent/$1.$2 break;
    }
  }
