---

php_brew_fpm_config:
  - option: "group"
    section: "www"
    value: "vagrant"

php_ondrej_versions:
  - 'php5.6'
  - 'php7.0'

php_ondrej_apt_packages:
  - 'php5.6'
  - 'php5.6-fpm'
  - 'php7.0'
  - 'php7.0-fpm'

php_ondrej_pool_defaults:
  chdir: /
  user: vagrant
  group: vagrant
  listen.owner: vagrant
  listen.group: vagrant
  pm: dynamic
  pm.max_children: 5
  pm.start_servers: 2
  pm.min_spare_servers: 1
  pm.max_spare_servers: 3

php_ondrej_pools:
  - name: default
    listen: "/var/run/php/version-fpm.sock"
  - name: xhprof
    listen: "/var/run/php/version-fpm.xhprof.sock"
    "php_admin_value[auto_prepend_file]": "{{ typo3_webroot }}/xhprof.local.typo3.org/external/header.php"

php_ondrej_ini:
  - option: "engine"
    section: "PHP"
    value: "1"
  - option: "error_reporting"
    section: "PHP"
    value: "E_ALL & ~E_DEPRECATED & ~E_STRICT"
  - option: "expose_php"
    section: "PHP"
    value: "On"
  - option: "date.timezone"
    section: "PHP"
    value: "{{ timezone }}"
  - option: "max_execution_time"
    section: "PHP"
    value: 240
  - option: "upload_max_filesize"
    section: "PHP"
    value: "20M"
  - option: "post_max_size"
    section: "PHP"
    value: "20M"
  - option: "soap.wsdl_cache_dir"
    section: "soap"
    value: "/tmp"
  - option: "pdo_mysql.cache_size"
    section: "Pdo_mysql"
    value: "2000"
  - option: "sendmail_path"
    section: "mail function"
    value: "/opt/mailhog/mailhog"

php_brew_enable: yes

# Make sure you also adjust the upstreams in nginx_configs after changing this
php_brew_versions:
  - '5.5.32'
